version: '3'
services:
  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    ports:
      - 3000:80

  backend:
    build: ./backend
    image: backend
    container_name: backend
    ports:
      - 5000:5000
